# Generated by Django 4.2.7 on 2024-03-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_newsuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsUser',
        ),
    ]
