# Generated by Django 4.2.7 on 2024-03-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Us',
            new_name='Contact_Us_db',
        ),
    ]
