# Generated by Django 4.2.7 on 2024-03-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_rename_contact_us_contact_us_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us_db',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ ارسال'),
        ),
    ]
