# Generated by Django 4.2.7 on 2024-03-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_contact_us_db_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us_db',
            name='readed_by_admin',
            field=models.BooleanField(default=False, null=True, verbose_name='خوانده شده توسط ادمین'),
        ),
    ]
