# Generated by Django 4.2.7 on 2024-03-16 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0005_producdt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='تگ فارسی')),
                ('tag_url', models.CharField(max_length=50, verbose_name='تگ انگلیسی محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Index.producdt')),
            ],
        ),
    ]
